askme/urls.py
from django.urls import path
from django.conf.urls import url, include
from . import views


urlpatterns = [
    path(r'email/', views.emailView, name='email'),
]

blog/urls.py
from django.conf.urls import url, include
from django.views.generic import ListView, DetailView
from blog.models import Post

urlpatterns = [
    url(r'^$', ListView.as_view(queryset=Post.objects.all()[:25], template_name='blog/blog.html')),
    url(r'^(?P<pk>\d+)$', DetailView.as_view(model=Post, template_name='blog/post.html'))
]

main/urls.py
from django.urls import path
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^about/', views.about, name='about'),
]

personal_site/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('main.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^semantic/', include('semantic.urls')),
    url(r'', include('askme.urls')),
]

semantic/urls.py
from django.urls import path
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.semantic, name='semantic'),
    url(r'^thanks', views.thanks, name='thanks'),
    url(r'^review/', views.review, name='review'),
]

askme/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=140)
    body = models.TextField()
    date = models.DateTimeField()

    def __str__(self):
        return self.title




main/models.py
from django.db import models

# Create your models here.

semantic/models.py
from django.db import models

# Create your models here.

askme/forms.py
from django import forms

class ContactForm(forms.Form):
    email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

askme/views.py
# sendemail/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import ContactForm


def emailView(request):
    sended = False
    message_client = "Thanks for your question! I will try to answer in near time.\n\n\n" \
                     "Rudnitskiy Andrey"
    admin_email = 'mail@arudnitskiy.ru'

    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            message = 'From email: ' + from_email + '\n' + message
            recipients = ['andre.rudnitskii@yandex.ru']
            try:
                send_mail(subject, message, admin_email, recipient_list=recipients)
                sended = True
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            try:
                send_mail(subject, message_client, admin_email, recipient_list=[from_email])
            except:
                return HttpResponse('Invalid header found.')

            render(request, "askme/askme.html", {'form': form, 'sended': sended})

    return render(request, "askme/askme.html", {'form': form, 'sended': sended})

blog/views.py
from django.shortcuts import render

# Create your views here.

main/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'personal/home.html')


def contact(request):
    return render(request, 'personal/contacts.html', context={'email': 'mail@arudnitskiy.ru',
                                                              'phone': '+7(977)-269-6705',
                                                              'address':'Moscow',
                                                     })

def about(request):
    return render(request, 'personal/about.html')

semantic/views.py
from django.shortcuts import render
import re
import os
import sys

cur_dir = os.path.dirname(__file__)
sys.path.append(os.path.join(cur_dir, 'classifier'))
import classifier


# Create your views here.
def semantic(request):
    return render(request, 'semantic/description.html')


def thanks(request):
    print(request.POST)
    return render(request, 'semantic/thanks.html')


def review(request):
    labels = {0: 'negative', 1: 'positive'}
    if request.method == 'POST':
        text_review = request.POST['review']
        print(text_review)
        matching = bool(re.match("^[а-яА-Я]*$", text_review))
        print(matching)
        if len(text_review) < 15:
            return render(request, 'semantic/review.html', context={'value_field': 'Enter more than 15 symbols...'})
        else:
            if matching:
                return render(request, 'semantic/review.html', context={'value_field': 'Enter only English letters...'})
            else:
                prediction, probability = classifier.classify(text_review)
                classifier.push_review(text_review, prediction)
                probability = round(probability,3)
                prediction_label = labels[prediction]
                return render(request, 'semantic/results.html', context={'probability': probability,
                                                                         'prediction': prediction_label,
                                                                         'text_review': text_review
                                                                         })
    else:
        return render(request, 'semantic/review.html', context={'value_field': 'Only english language...'})
        # return render(request, 'semantic/review.html')

askme/templates/askme/askme.html
{% extends "personal/index.html" %}

{% block main %}
<center>
    <h3>Ask me</h3>
</center>
<br>
<form method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="container">
        <div class="col">
            <center>
                <div class="fieldWrapper col-8">
                    {{ form.subject.errors }}
                    <label for="id_subject">Email subject:</label>
                    <textarea class="form-control" id="id_subject" name="subject" rows="1" cols="10"></textarea>
                </div>
                <div class="fieldWrapper col-8">
                    <br>
                    {{ form.email.errors }}
                    <center><label for="id_email">Your email address:</label>
                        <textarea class="form-control" id="id_email" name="email" rows="1" cols="2"></textarea>
                    </center>
                </div>
                <div class="col-8">
                    <br>
                    {{ form.message.errors }}
                    <center><label for="id_message">Your message:</label>
                        <textarea class="form-control" id="id_message" name="message" rows="5" cols="2"></textarea>
                    </center>
                </div>
                <p>
                <center>
                    <button type="submit" class="btn btn-primary mx-sm-2 mb-2">Send</button>
                </center>
                </p>
                {% if sended %}
                <label for="id_message">Thanks! Your message was sent! </label>
                {% endif %}
            </center>
        </div>
    </div>
</form>
{% endblock %}

blog/templates/blog/blog.html
{% extends "personal/index.html" %}

{% block main %}
    {% for post in object_list %}
        <!--<h5> {{ post.date|date:"Y-m-d" }} <a href="/blog/{{post.id}}">  {{post.title}} </a></h5>-->
        <div class="row">
          <div class="col-sm-6">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title"></h5>
                <p class="card-text">{{ post.date|date:"Y-m-d"}}</p>
                <a href="/blog/{{post.id}}" class="btn btn-primary">{{post.title}}</a>
              </div>
            </div>
          </div>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/post.html
{% extends "personal/header.html" %}

{% block content %}
     <h3>{{post.title}}</h3>
     <h6> on {{post.date}}</h6>
    {{post.body|safe|linebreaks}}
{% endblock %}

main/templates/personal/about.html
{% extends "personal/index.html" %}

{% block main %}
<center>
    <h3>About</h3>
</center>
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-4">
            <img src="/static/img/profile.jpeg" width="200px" height="250px">
        </div>
        <div class="col-8">
            <table class="table table-bordered">
                <thead>
                <tr></tr>
                </thead>
                <tbody>
                <tr>
                    <th scope="row">BIO</th>
                    <td>Rudnitskiy Andrey,<br>
                        16 May 1994<br>
                    </td>
                </tr>
                <tr>
                    <th scope="row">Education</th>
                    <td><a class="link" href="https://miet.ru/">Moscow Institute of Electronic Technology </a>,<br>
                        Baschelor's degree 2016,<br>
                        Master's degree 2018
                    </td>
                </tr>
                <tr>
                    <th scope="row">Experience</th>
                    <td>
                        <a href="http://www.niime.ru/en/" class="link">JSC Molecular Electronics Research Institute</a>,<br>
                        data scientist and software developer,<br>
                        2 years
			<br>
			Samsung Research Center, data scientist <br>
		        1 year
                    </td>

                </tr>
                <tr>
                    <th scope="row">Projects</th>
                    <td>
                        - Analysis of time series of power microelectronic devices to check safety,<br>
                        - Developing different tools for data analysis (with Kmeans, MLP, CNN),<br>
                        - Creating web-projects with Django (landing pages, personal sites),<br>
                        - Creating chat-bots in Telegram,<br>
			- Forecasting sell-out in Samsung products in Russia(boosting,lstm network)<br>
			- Segmentation clients on groups<br>
                        - Training on different tasks from machine learning area(computer vision with object detection and recognition)		
                    </td>
                </tr>
                <tr>
                    <th scope="row">Hobbies</th>
                    <td>
                        - Sports(football, basketball, hockey),<br>
                        - Reading books,<br>
                        - Coding
                    </td>
                </tr>
                <tr>
                    <th scope="row">Languages</th>
                    <td>
                        - Englsih: intermediate,<br>
                        - Russian: advanced
                    </td>
                </tr>
                </tbody>
            </table>

        </div>
        <div class="col">
        </div>
        <div class="w-100"></div>
        <br>
        <div class="col">
        </div>
        <div class="col">

        </div>
        <div class="col">
        </div>
    </div>
</div>


{% endblock %}

main/templates/personal/contacts.html
{% extends "personal/index.html" %}

{% block main %}

<center><h3>Contact</h3></center>
<br>
<div class="container">
    <div class="row">
        <div class="col-4">
            <p2>
                <br>
                <strong><span style="font-size:18px;">Rudnitskiy.Inc</span></strong>
                <br>
                <br>
                Moscow, Russia
                <br>
                <br>
                Tel: +7 (977)-269-67-05 <br>
                <a href="mailto:{{ email }}">Email: {{ email }}</a>
            </p2>
        </div>
        <div class="col-8" id="map-canvas"
             style="width:400px;height:500px;">
        </div>
    </div>
</div>
<script>

function initMap() {
  var myLatlng = new google.maps.LatLng(55.870833,37.490336);
  var mapOptions = {
    zoom: 6,
    center: myLatlng
  }

  var usRoadMapType = new google.maps.StyledMapType([{"stylers":[{"saturation":-100},{"gamma":1}]},{"elementType":"labels.text.stroke","stylers":[{"visibility":"off"}]},{"featureType":"poi.business","elementType":"labels.text","stylers":[{"visibility":"off"}]},{"featureType":"poi.business","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"poi.place_of_worship","elementType":"labels.text","stylers":[{"visibility":"off"}]},{"featureType":"poi.place_of_worship","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"road","elementType":"geometry","stylers":[{"visibility":"simplified"}]},{"featureType":"water","stylers":[{"visibility":"on"},{"saturation":50},{"gamma":0},{"hue":"#50a5d1"}]},{"featureType":"administrative.neighborhood","elementType":"labels.text.fill","stylers":[{"color":"#333333"}]},{"featureType":"road.local","elementType":"labels.text","stylers":[{"weight":0.5},{"color":"#333333"}]},{"featureType":"transit.station","elementType":"labels.icon","stylers":[{"gamma":1},{"saturation":50}]}], {name: 'US Road Atlas'});

  var marker = new google.maps.Marker({
      position: myLatlng,
      title:"Rudnitskiy",
      animation: google.maps.Animation.DROP,
      icon: "/static/img/marker.png"
  });

  var map = new google.maps.Map(document.getElementById('map-canvas'), {
    zoom: 12,
    center: {lat: 55.870388, lng: 37.490336},
    mapTypeControlOptions: {
      mapTypeIds: [google.maps.MapTypeId.ROADMAP, 'usroadatlas']
    }
  });

  marker.setMap(map);

  map.mapTypes.set('usroadatlas', usRoadMapType);
  map.setMapTypeId('usroadatlas');
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCwy61PvZ52sOF61fl71x4QycgJ_8xQq94&callback=initMap"
        async defer></script>
<div class="col-xs-12" style="height:250px; margin-bottom:250px;"></div>
{% endblock %}



main/templates/personal/home.html
{% extends "personal/index.html" %}

{% block main %}
<!--Block-->
<section id="welcome" background="static/img/bachelor.png">
    <center><h2>Welcome to my site</h2>
        <br>
        <h5>I'm glad to see you here. I hope that my site can help you.</h5>
        <h5>I have tried to tell you about me and show some projects. </h5>
    </center>
</section>
<!--------------------------------------------------------------------------------------------------------------------->
<section id="education">
    <div class="line"></div>
    <h2>
        <center>Education</center>
    </h2>
    <br>
    <center>
        <h4>Moscow Institute of Electronic Technology</h4>
    </center>
    <br>

    <div class="container">
        <div class="row">
            <div class="col">
                <center><img src="static/img/bachelor.png" style="width:200px;height:200px"></center>
            </div>
            <div class="col">
                <center><img src="static/img/master.png" style="width:200px;height:200px"></center>
            </div>
            <div class="w-100"></div>
            <br>
            <div class="col">
                <center><h4>Bachelor's degree in computer science</h4></center>
            </div>
            <div class="col">
                <center><h4>Master's degree in computer science</h4></center>
            </div>
        </div>
    </div>
</section>
<!-------------------------------------------------------------------------------------------------------------------->

<section id="softskills">
    <div class="line"></div>
    <center><h2>Soft skills</h2></center>
    <br>
    <br>
    <div class="container">
        <div class="row">
            <div class="col">
                <center><img src="static/img/analthink.png" style="width:100px;height:100px"></center>
            </div>
            <div class="col">
                <center><img src="static/img/purpose.png" style="width:100px;height:100px"></center>
            </div>
            <div class="col">
                <center><img src="static/img/teamwork.png" style="width:100px;height:100px"></center>
            </div>
            <div class="w-100"></div>
            <br>
            <div class="col">
                <center><h4>Analytical thinking</h4></center>
            </div>
            <div class="col">
                <center><h4>Productive</h4></center>
            </div>
            <div class="col">
                <center><h4>Team player</h4></center>
            </div>
        </div>
    </div>
</section>
<!--------------------------------------------------------------------------------------------------------------------->
<section id="hardskills">
    <div class="line" style="solid"></div>
    <center><h2>Hard Skills</h2></center>
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col">
                <center><img src="static/img/python.png" style="width:200px;height:180px"></center>
            </div>
            <div class="col">
                <center><img src="static/img/ml.png" style="width:250px;height:200px"></center>
            </div>
            <br>
            <div class="w-100"></div>
            <br>
            <div class="col">
                <center><h4>Django, SqlAlchemy, PyQt, Built-in</h4></center>
            </div>
            <div class="col">
                <center><h4>MatPlotLib, Pandas, NumPy, Keras, SciKitLearn</h4></center>
            </div>

        </div>
    </div>
</section>
<!--------------------------------------------------------------------------------------------------------------------->
<section id="progskills">
    <div class="line"></div>
    <center><h2>Programming skills</h2></center>
    <br>
    <div class="progress">
        <div class="progress-bar bg-danger" role="progressbar" style="width: 33%" aria-valuenow="33" aria-valuemin="0"
             aria-valuemax="90">Junior
        </div>
        <div class="progress-bar bg-warning" role="progressbar" style="width: 33%" aria-valuenow="33" aria-valuemin="0"
             aria-valuemax="90">Middle
        </div>
        <div class="progress-bar bg-success" role="progressbar" style="width: 34%" aria-valuenow="33" aria-valuemin="0"
             aria-valuemax="90">Senior
        </div>
    </div>
    <br>
    <h4>Python</h4>
    <div class="progress">
        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: 65%;"
             aria-valuenow="25"
             aria-valuemin="0" aria-valuemax="100">65%
        </div>
    </div>
    <br>
    <h4>C/C++</h4>
    <div class="progress">
        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: 35%;"
             aria-valuenow="35"
             aria-valuemin="0" aria-valuemax="100">35%
        </div>
    </div>
    <br>
    <h4>SQL</h4>
    <div class="progress">
        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: 30%;"
             aria-valuenow="30"
             aria-valuemin="0" aria-valuemax="100">30%
        </div>
    </div>
    <br>
    <h4>Java</h4>
    <div class="progress">
        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: 25%;"
             aria-valuenow="25"
             aria-valuemin="0" aria-valuemax="100">25%
        </div>
    </div>
    <br>
    <br>
</section>
{% endblock %}

main/templates/personal/index.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Rudnitskiy Andrey</title>
    <link rel="shortcut icon" href="/static/img/favicon.png" type="image/x-icon">
    <link rel="icon" href="static/img/favicon.png" type="image/x-icon">
    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="/static/css/style.css">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"
            integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ"
            crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"
            integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY"
            crossorigin="anonymous"></script>

</head>

<body>

<div class="wrapper">
    <!-- Sidebar  -->
    <nav id="sidebar">
        <div class="sidebar-header">
            <h3>Rudnitskiy Andrey</h3>
            <strong>RA</strong>
        </div>

        <ul class="list-unstyled components">
            <li class="active">
                <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <i class="fas fa-home"></i>
                    Home
                </a>
                <ul class="collapse list-unstyled" id="homeSubmenu">
                    <li>
                        <a class="page-scroll" href="/#education">Education</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/#softskills">Soft skills</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/#hardskills">Hard skills</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/#progskills">Programming skills</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="/about">
                    <i class="fas fa-briefcase"></i>
                    About
                </a>
            </li>
            <li>
                <a href="#portfolioSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <i class="fas fa-image"></i>
                    Portfolio
                </a>
                <ul class="collapse list-unstyled" id="portfolioSubmenu">
                    <li><a href="/semantic">Semantic Analysis</a></li>
                </ul>
            </li>
            <li>
                <a href="/email">
                    <i class="fas fa-question"></i>
                    Ask me
                </a>
            </li>
            <li>
                <a href="/contact">
                    <i class="fas fa-paper-plane"></i>
                    Contact
                </a>
            </li>
        </ul>

        <ul class="list-unstyled CTAs">
            <li>
                <a href="https://github.com/amunra94" class="download">Go to GitHub</a>
            </li>
            <!--<li>-->
            <!--<a href="https://github.com/amunra94" class="article">Go to GitHub</a>-->
            <!--</li>-->
        </ul>
        <footer class="bar-footer font-small blue pt-4">
            <div class="footer-copyright text-center py-3">
                <p2><a href="https://vk.com/normandec94" target="_blank"> Vk </a> |
                    <a href="https://twitter.com/amunra9494" target="_blank"> Twitter</a> |
                    <a href="https://www.instagram.com/andreybigboy/" target="_blank"> Instagram </a>
                </p2>
            </div>
            <br>
            <div class="footer-copyright text-center py-3">© 2018 Created by:
                <a href="/#"> Rudnitskiy Andrey</a>
            </div>
        </footer>
    </nav>

    <!-- Page Content  -->
    <div id="content">

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">

                <button type="button" id="sidebarCollapse" class="btn btn-info">
                    <i class="fas fa-align-left"></i>
                    <span>Menu</span>
                </button>

                <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fas fa-align-justify"></i>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="nav navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/about">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/email">Ask me</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/contact">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block main %}
        {% endblock %}


    </div>
</div>

<script src="{% static 'creative/js/jquery.easing.min.js' %}"></script>
<!-- jQuery CDN - Slim version (=without AJAX) -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<!-- Popper.JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
        integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
        crossorigin="anonymous"></script>
<!-- Bootstrap JS -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
        integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
        crossorigin="anonymous"></script>

<script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });












</script>


</body>

</html>

semantic/templates/semantic/description.html
{% extends "semantic/semantic.html" %}

{% block semantic_main %}

<h4>Prediction the mood of the movie review.</h4>
<br>
<h5>Description task:</h5>
<p2> Dataset of IMDB with 50.000 movie reviews on English: 25.000 - negative and 25.000 - positive.<br>
    Need to fit model to predict of mood review.
</p2>

<div class="line"></div>

<h5>How have i done it?</h5>
<p2>
    <strong>Preparing:</strong><br>
    I've cleared data from of frequent word like (and,or..) and special symbols.<br>
    I have used NLTK library for downloading English stop-words.<br>
    In this task I used bag-of-word technique to convert words to numbers
    and tf-idf method to normalize weight of some words.<br>
    <br>
    <strong>Analysis:</strong><br>
    I've taken SGDClassifier with LogRegression as a model for training with one sample.<br>
    For finding good parameter I used GridSearch method with different parameters (StemmerPorter, Snowball) <br>
    In the end I embedded this model in my personal site. Jus click the button below and test model.
    <br>
    Accuracy of this model: 90%.
</p2>
<div class="line"></div>
<a href="review/" class="btn btn-primary " role="button" aria-pressed="true">Test model</a>

{% endblock %}

semantic/templates/semantic/results.html
{% extends "semantic/semantic.html" %}

{% block semantic_main %}
<h5><strong>Your review:</strong></h5>

{{ text_review }}

<div class="line"></div>
<h5><strong>Prediction:</strong></h5>
<div>
    This review is <strong> {{prediction}} </strong>.
    <br>
    Probability of prediction: <strong>{{probability}}% </strong>.
</div>
<form action="../thanks/" method="post">
    {% csrf_token %}
    <br>
    <button type="submit" name="feedback_button" class="btn btn-primary" value="right">Correctly</button>
    <button type="submit" name="feedback_button" class="btn btn-primary " value="wrong">Not correctly</button>
</form>


{% endblock %}

semantic/templates/semantic/review.html
{% extends "semantic/semantic.html" %}

{% block semantic_main %}
<br>
<center><h5>Please, enter your movie review:</h5></center>
<br>
<form class="form-inline" action="" method="post">
    {% csrf_token %}
    <!--{{ form.as_p }}-->
    <div class="container">
        <div class="row">
            <div class="col">
            </div>
            <div class="col">
                <center>
                    <div class="form-group">
                        <textarea class="form-control" id="review_form" name="review" rows="8" cols="45"
                                  placeholder="{{value_field}}"></textarea>
                    </div>
                </center>
            </div>
            <div class="col">
            </div>
            <div class="w-100"></div>
            <br>
            <div class="col">
            </div>
            <div class="col">
               <center><button type="submit" class="btn btn-primary mx-sm-2 mb-2">Send</button></center>
            </div>
            <div class="col">
            </div>
        </div>
    </div>



</form>


{% endblock %}

semantic/templates/semantic/semantic.html
{% extends "personal/index.html" %}

{% block main %}

<center>
    <h3>Semantic Analysis</h3>
</center>

{% block semantic_main %}
{% endblock %}

{% endblock %}



semantic/templates/semantic/thanks.html
{% extends "semantic/semantic.html" %}

{% block semantic_main %}
<h5>Thanks for your help!</h5>
<br>
<a href="/semantic/review" class="btn btn-primary " role="button" aria-pressed="true">Add new review</a>

<!--<br>-->
<!--<div>{{text_review}}</div>-->
<!--<br>-->
<!--<h3>Предсказание:</h3>-->
<!--<div>-->
    <!--Данный киноотзыв является <strong> {{prediction}} </strong>.-->
    <!--<br>-->
    <!--Вероятность правильности прогноза: {{probability}}%.-->
<!--</div>-->
{% endblock %}